-- 各期紙本印製紀錄
-- 資料來源：與國北數位（復興店）的 LINE 對話逐筆整理。
-- 僅登入者可讀寫（印量屬內部營運資料，前台 /publication 不顯示）。

create table if not exists public.issue_print_runs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  issue integer not null references public.issues (id) on delete cascade,
  print_date date not null,
  copies integer not null check (copies > 0),
  is_reprint boolean not null default false,
  vendor text default '國北數位（復興店）',
  note text
);

create index if not exists issue_print_runs_issue_idx
  on public.issue_print_runs (issue, print_date);

alter table public.issue_print_runs enable row level security;

drop policy if exists "print runs staff select" on public.issue_print_runs;
create policy "print runs staff select"
  on public.issue_print_runs for select
  to authenticated
  using (true);

drop policy if exists "print runs staff insert" on public.issue_print_runs;
create policy "print runs staff insert"
  on public.issue_print_runs for insert
  to authenticated
  with check (true);

drop policy if exists "print runs staff update" on public.issue_print_runs;
create policy "print runs staff update"
  on public.issue_print_runs for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "print runs staff delete" on public.issue_print_runs;
create policy "print runs staff delete"
  on public.issue_print_runs for delete
  to authenticated
  using (true);
