create table if not exists public.issue_9_payment_orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  email text not null,
  copies integer not null check (copies between 1 and 1000),
  unit_price integer not null default 350 check (unit_price > 0),
  amount integer generated always as (copies * unit_price) stored,
  last5 text not null check (last5 ~ '^[0-9]{5}$'),
  message text,
  note text,
  confirmed boolean not null default false,
  confirmed_at timestamptz,
  confirmation_email_sent_at timestamptz
);

create index if not exists issue_9_payment_orders_created_at_idx
  on public.issue_9_payment_orders (created_at desc);

alter table public.issue_9_payment_orders
  alter column amount set not null;

create index if not exists issue_9_payment_orders_confirmed_idx
  on public.issue_9_payment_orders (confirmed, created_at desc);

alter table public.issue_9_payment_orders enable row level security;

drop policy if exists "issue 9 orders staff select" on public.issue_9_payment_orders;
create policy "issue 9 orders staff select"
  on public.issue_9_payment_orders for select
  to authenticated
  using (true);

drop policy if exists "issue 9 orders staff update" on public.issue_9_payment_orders;
create policy "issue 9 orders staff update"
  on public.issue_9_payment_orders for update
  to authenticated
  using (true)
  with check (true);
